### ISSUE TITLE
[Security] Disable relative paths loading

### ISSUE THREAD

**Issue by drupol** [ec-europa/ecl-twig#126]
Hi all,

Some comments are relying on relative paths to load component into a component.

Ex: https://github.com/ec-europa/ecl-twig/blob/master/src/ec/packages/ec-component-button/button.html.twig#L58

I just had a discussion with the core Twig developers and apparently loading relative paths from a Twig template is not supported.
This is why Twig asks to define the paths where to look for templates.

This is apparently also for security matters.

Therefore, I would ask you guys if it would be possible to change from

```
      {% include '../ec-component-icon/icon.html.twig' with {
```

to

```
      {% include 'ec-component-icon/icon.html.twig' with {
```

Once this is done, we will be able to provide a Symfony bundle including the different flavors of ECL using Twig.

Thx

**Comment by ademarco** [comment]
We would also prefer not to have relative path in Twig templates. Anyway, until this is fixed, the [ECL Twig Loader](https://github.com/openeuropa/ecl-twig-loader) project can be used, it's `dev-master` supports ECL Twig way of using relative paths.

**Comment by drupol** [comment]
Thanks, we already evaluated it but here the idea is to not rely on another tool and to fix issue at the root directly.

[ECL Twig Loader](https://github.com/openeuropa/ecl-twig-loader) would have been an option but it requires to change the default Twig loader, or replace it with a Chain loader and add it there. To be honest, this is too much of a hassle already.

I'd like to hear from the maintainers what they think about this.

Thx
