### ISSUE TITLE
[Releases] - Update to ECL 2.11.0

### ISSUE THREAD

**Issue by planctus** [ec-europa/ecl-twig#127]
- [Checkbox] New component - https://github.com/ec-europa/europa-component-library/pull/984

**https://webgate.ec.europa.eu/CITnet/jira/browse/TWIG-9** :green_heart:

 - [File upload] New component - https://github.com/ec-europa/europa-component-library/pull/1247

**https://webgate.ec.europa.eu/CITnet/jira/browse/TWIG-30**  :green_heart:

 - [Date block] New component - https://github.com/ec-europa/europa-component-library/pull/1231

**https://webgate.ec.europa.eu/CITnet/jira/browse/TWIG-31**  :green_heart:

- [Auto-init-javascript] - Investigation - https://github.com/ec-europa/europa-component-library/pull/1227 :green_heart:

**https://webgate.ec.europa.eu/CITnet/jira/browse/TWIG-32** 

 - [Dropdown] New component - from ECL v1 (legacy) - INNO-1725 https://github.com/ec-europa/europa-component-library/pull/1262

**https://webgate.ec.europa.eu/CITnet/jira/browse/TWIG-3**  :green_heart:

- [Card] Update - https://github.com/ec-europa/europa-component-library/pull/1253 
                            https://github.com/ec-europa/europa-component-library/pull/1253

**https://webgate.ec.europa.eu/CITnet/jira/browse/TWIG-33** :green_heart:

- [Form-group] Update - ec-europa/europa-component-library#1233 

**https://webgate.ec.europa.eu/CITnet/jira/browse/TWIG-35** :green_heart:

- [Radio] - https://github.com/ec-europa/europa-component-library/pull/1222

**https://webgate.ec.europa.eu/CITnet/jira/browse/TWIG-36** :green_heart:

- [select] update styling of select 

**https://webgate.ec.europa.eu/CITnet/jira/browse/TWIG-37** :green_heart:

- [text-inputs] update styling of text inputs ec-europa/europa-component-library#1183

**https://webgate.ec.europa.eu/CITnet/jira/browse/TWIG-38** :green_heart:

- [Description list] Update - Add horizontal variant - ec-europa/europa-component-library#1275

**https://webgate.ec.europa.eu/CITnet/jira/browse/TWIG-39** :green_heart:

- [site-header] bridge language selector and overlay https://github.com/ec-europa/europa-component-library/pull/1267

**https://webgate.ec.europa.eu/CITnet/jira/browse/TWIG-40** :green_heart:

- [Footer]  - Refactor markup

**https://webgate.ec.europa.eu/CITnet/jira/browse/TWIG-41** :green_heart:

- [Media-container] - Refactor markup

**https://webgate.ec.europa.eu/CITnet/jira/browse/TWIG-42** :green_heart:

- [Textarea] - Updates

**https://webgate.ec.europa.eu/CITnet/jira/browse/TWIG-49** :green_heart:

- [Search form] - Updates

**https://webgate.ec.europa.eu/CITnet/jira/browse/TWIG-50** :green_heart:

- [various] - Removing hide_label parameter

**https://webgate.ec.europa.eu/CITnet/jira/browse/TWIG-52** :green_heart:

- [Lists] - Adding variant parameter and examples for no-bullet and divider modifiers.

**https://webgate.ec.europa.eu/CITnet/jira/browse/TWIG-59**  :green_heart:

- [Hero banner] - Applying the cta variant to the button

**https://webgate.ec.europa.eu/CITnet/jira/browse/TWIG-60**  :green_heart:

- [In page navigation] - Fixing demo markup for the inpage navigation component.

**https://webgate.ec.europa.eu/CITnet/jira/browse/TWIG-61**  :green_heart:

- [Tag] - Add button version.

**https://webgate.ec.europa.eu/CITnet/jira/browse/TWIG-62**  :green_heart:

**Comment by kieleda** [comment]
- [Form-group] Update - ec-europa/europa-component-library#1233
**https://webgate.ec.europa.eu/CITnet/jira/browse/TWIG-35**
- [Radio] - ec-europa/europa-component-library#1222
**https://webgate.ec.europa.eu/CITnet/jira/browse/TWIG-36**
- [select] update styling of select ec-europa/europa-component-library#1228
**- https://webgate.ec.europa.eu/CITnet/jira/browse/TWIG-37**
- [text-inputs] update styling of text inputs ec-europa/europa-component-library#1183
**https://webgate.ec.europa.eu/CITnet/jira/browse/TWIG-38**
- [Description list] Update - Add horizontal variant - ec-europa/europa-component-library#1275
**https://webgate.ec.europa.eu/CITnet/jira/browse/TWIG-39**
- [site-header] bridge language selector and overlay https://github.com/ec-europa/europa-component-library/pull/1267
**https://webgate.ec.europa.eu/CITnet/jira/browse/TWIG-40**
