### ISSUE TITLE
Provide composer.json

### ISSUE THREAD

**Issue by drupol** [ec-europa/ecl-twig#130]
Hi,

In order to let people download this package through Composer (_the PHP package manager_), it needs to be available on [Packagist](https://packagist.org).

In order to have a package on Packagist, it **must** contains a `composer.json` file.

Having a `composer.json` file in the project is harmless. Unlike npm, you don't have to worry about the releases and stuff, releases are automatically published based on tags.

We need this file in the project to reduce the number of external tool needed for the installation of ECL Twig in any PHP applications. There is no need to use an external tooling for downloading the proper version of the package while Composer is able to do it properly.

Thanks.

**Comment by planctus** [comment]
Ciao @drupol, we added a composer.json in https://github.com/ec-europa/ecl-twig/pull/162 together with the introduction of the libraries for linting the templates and the fixes on those templates, if you're happy with this implementation we can close the related issues here on github, We don't have yet a plan about the next release, but this could easily go in a new patch to be released in ecl-twig only, most likely a 2.11.1, if everything looks fine we might release it soon.

**Comment by drupol** [comment]
Excellent, I will close the issue and my PR now. THANKS !

Next step: make it available on [packagist.org](https://packagist.org).
