### ISSUE TITLE
Twig template checkstyle

### ISSUE THREAD

**Issue by drupol** [ec-europa/ecl-twig#145]
Hi,

I discovered this package recently: [friendsoftwig/twigcs](https://github.com/friendsoftwig/twigcs) and I think it might be useful for you guys.

Basically it's a codestyle checker for `.twig` files based on [an official ruleset](https://twig.symfony.com/doc/2.x/coding_standards.html).

Here's the log of the result when I run this against the repo: https://pastebin.com/kpmMjpNX

I noticed that there are some false positive, but overal it gives you some hints on how to improve and standardize the `.twig` files.

**Comment by planctus** [comment]
Thanks @drupol, think this a very hot topic, we need to improve the overall quality of the templates, as this tool shows we have many inconsistencies, glitches, issues of different type. Mind just the fact that we write TWIG 1, we'll come out with something on this soon.

**Comment by drupol** [comment]
Hi,

Code style and check style is always a hot topic... I reaaaally know what you're talking about.
I was just sharing that tool that I didn't know and that I found really cool to align developers, without spending time discussion how things should be written.

That said, if you'll come out with something soon, I can't wait to see :-)

**Comment by drupol** [comment]
See #162
