### ISSUE TITLE
Submit the package on packagist.org

### ISSUE THREAD

**Issue by drupol** [ec-europa/ecl-twig#166]
We should submit this package on [packagist.org](https://packagist.org) so it's available through Composer (`$ composer require ec-europa/ecl-twig`).

I don't know who's in charge of the `ec-europa` namespace on Packagist, but we will need him to fix this.

**Comment by planctus** [comment]
We plan to do this together with the next release, would you please take care yourself @drupol of the packagist situation regarding the organisation and the rest so that we do this smoothly when it's time? ;)

**Comment by drupol** [comment]
I wish I could @planctus and I'll be glad to submit it, but I don't have the rights to do it.

There is someone in D1 team which is admin of this namespace, and I don't know who it is.

I will try to ask here and there and report here asap.

**Comment by drupol** [comment]
Any news on this @planctus  ?

**Comment by planctus** [comment]
https://packagist.org/packages/ec-europa/ecl-twig ;)

**Comment by drupol** [comment]
Thanks !
