### ISSUE TITLE
Update documentation - Node 10 is the minimal Node version to use

### ISSUE THREAD

**Issue by drupol** [ec-europa/ecl-twig#177]
Since #168 , the minimum version of Node is 10 instead of 8.

The [documentation](https://github.com/ec-europa/ecl-twig/blob/master/docs/getting-started.md) needs to be updated to reflect that change.

**Comment by planctus** [comment]
We updated it, going to be fixed in 2.12.0, thanks for posting this, @drupol  ;)

**Comment by drupol** [comment]
Thanks !
