### ISSUE TITLE
What would be the best approach about namespaces?

### ISSUE THREAD

**Issue by planctus** [ec-europa/ecl-twig#179]
At the moment we are about to move to a namespaced approach for including templates.
In https://github.com/ec-europa/ecl-twig/pull/164 we have a working implementation using 
[twing](https://www.npmjs.com/package/twing,) it defines one single namespace @ecl-twig so that the templates are included like this: `include @ecl-twig/template.twig`

This approach works as long as we don't have templates with the same name in different folders, which is not the case for now but at the same time we might want to do this future-proof (relatively..) from the beginning and so we might want to evaluate alternatives:

### General namespace

 `include @ecl-twig/template.twig`

Each of the containing folders for templates is added to the namespace, therefore we only need the template name to load it, this is the current implementation in TWIG-63 and it would fail in case we have two templates with the same name in different folders, basically.

### General namespace, specifying the folder

`include @ecl-twig/containingFolder/template.twig`

In this case we would keep the single @ecl-twig namespace but we would still load the templates using the containing folder 

### Multiple namespaces
`include @containingFolder/template.twig`

In this case we would use the namespace not to identify the "library" but specifically to address the folder we want to use.

The possibilities are not over, i put here the ones i had in mind but feel free to propose alternatives ;)

@yhuard , @emeryro , @ademarco , @papegaill , @drupol , @voidtek

**Comment by yhuard** [comment]
I'm in favour of `General namespace, specifying the folder` because it's closer to what you're used to do when you import libs in Node.js for example. You start with the package name (e.g. `@ecl-twig/ec-component-button`), then you specify the name of the file (`template.twig`). No conflicts (except if you have multiple versions of `@ecl-twig/ec-component-button`), no need to maintain multiple namespaces (in Twig, you just define the namespace `@ecl-tiwg` to point to `node_modules/@ecl-twig`), I don't see any downsides. :) 

But I don't have the perspective of the platform, which actually has to consume these templates. My point of view is only consultative ;)

**Comment by planctus** [comment]
@ademarco, @voidtek,  we are waiting for your contribution to make this decision, since you are the main consumers of this library at the moment, we want to be sure you are comfortable with the choices we make and this is a "delicate" one. 
Personally speaking i prefer the current way, @ecl-twig/template.twig although it's clear that this would set a constraint on the templates name so that no template with the same name is shipped in the library, i see this constraint as acceptable compared to the "simplification" of the syntax needed to load a template from our library.
Additional reason for going to the 

> General namespace, specifying the folder

is that we would only need to specify one single folder assigning it to the namespace, while in the current approach each folder needs to be added to this namespace.
So, let's put it this way, i have a preference for the "general namespace" solution but i would still choose to go for the specification of the folder, that is safer, maybe wiser, so 
2 votes for 
> General namespace, specifying the folder

**Comment by ademarco** [comment]
Had a quick chat with @planctus , I'd also use the component directory name in the loader, so:
```@ecl-twig/ec-component-NAME/NAME.html.twig```

**Comment by planctus** [comment]
Ok, i'd say we have a decision... ;) Thanks guys
